### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by dsp56001** [IAMColumbia/obg-sim2kid#1]
The current build doesn't run 
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=OneButtonGame
  StackTrace:
   at OneButtonGame.PlayerController.Reset(Vector2 position) in C:\src\GitHub\Grading\obg-sim2kid\OneButtonGame\OneButtonGame\PlayerController.cs:line 31

Transform is null

**Comment by sim2kid** [comment]
I can't recreate the error. Try running the tagged release build [https://github.com/IAMColumbia/obg-sim2kid/releases/tag/0.2](https://github.com/IAMColumbia/obg-sim2kid/releases/tag/0.2)

**Comment by sim2kid** [comment]
Patched
